name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

permissions:
  actions: write
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.8

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint code
        run: bun run lint

      - name: Build projects
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          bun run build

      - name: Run tests
        run: bun run test

      - name: Build docs
        run: bun run doc

      - name: Pre-serve
        run: bun run pre-serve

      - name: Create github release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true

      - name: Upload github pages artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: './packages/examples/public/'

  deploy-pages:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
